sudo: required

services:
    - docker

os:
    - linux

script:
    - docker run -it osrf/ros2 /bin/bash -c "`ros_2_container_install.bash`"
    - docker cp 'docker ps -l -q':root/temp_ws/install.tar .
