sudo: required

services:
    - docker

os:
    - linux

script:
    - docker pull osrf/ros2
    - docker run -it osrf/ros2 /bin/bash
    - cd
    - mkdir -p temp_ws/src
    - cd temp_ws/src
    - git clone https://github.com/geoffviola/ros2_boost
    - cd ..
    - ament build
