os: Visual Studio 2015

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      CONFIG: Release
      PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - md C:\dev
  - ps: Invoke-WebRequest https://github.com/osrf/opensplice/releases/download/6.4.0-0/opensplice-Win64VS2013-with-VS2015-patch.zip -OutFile C:\dev\opensplice.zip
  - 7z x -bso0 C:\dev\opensplice.zip -oC:\dev
  - ps: Invoke-WebRequest https://github.com/ros2/ros2/releases/download/release-alpha8/ros2-alpha8-package-windows-opensplice.zip -OutFile C:\dev\ros2.zip
  - 7z x -bso0 C:\dev\ros2.zip -oC:\dev
  - ren C:\dev\ros2-windows ros2
  - dir C:\dev
  - dir C:\dev\ros2
  - cmd: set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"
  - ps: $setup_bat_content = Get-Content C:\dev\ros2\setup.bat -Raw
  - ps: $verbose_setup_bat_content = $setup_bat_content -replace "@echo off", "echo starting setup script"
  - ps: $verbose_setup_bat_content = $verbose_setup_bat_content -replace ":: generated from ament_package/template/prefix_level/setup.bat.in", "echo starting setup script"
  - ps: $verbose_setup_bat_content | Out-File -FilePath C:\dev\ros2\setup.bat
  - ps: Get-Content C:\dev\ros2\setup.bat -Raw
  - call C:\dev\setup.bat

before_build:
  - cd ..
  - md ros2-boost-ws
  - md ros2-boost-ws\src
  - mv ros2-boost ros2-boost-ws\src
  - cd ros2-boost-ws

build_script:
  - C:\dev\ros2\bin\ament.exe build
