os: Visual Studio 2015

environment:
  matrix:
  - GENERATOR: "Visual Studio 14 2015"
    CONFIG: Release

matrix:
  fast_finish: true

install:
  - md C:\dev
  - ps: Invoke-WebRequest https://github.com/ros2/ros2/releases/download/release-alpha8/ros2-alpha8-package-windows-opensplice.zip -OutFile C:\dev\ros2
  - 7z x C:\dev\ros2 -oC:\dev
  - ren C:\dev\ros2-windows ros2
  - call C:\dev\ros2\install\setup.bash

build_script:
  - dir
  - dir C:\dev
  - echo %cd%
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin;%PATH%
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\vsvars32.bat"